import type { Metadata } from "next";
import { Urbanist, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const outfit = Outfit({
  subsets: ["latin"],
});

const urbanuist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kora - Personalised AI Agent for developers. ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        outfit.className,
        urbanuist.className,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" richColors closeButton />
        {children}
      </body>
    </html>
  );
}
